language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.0
  - android-29
  - add-on
  - extra
licenses:
- android-sdk-license-.+
before_install:
- echo $TRAVIS_BUILD_NUMBER
- yes | sdkmanager "platforms;android-29"
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
#- "./gradlew assembleRelease"
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew assembleRelease; fi'
before_deploy:
  - echo gitVersion
  - git rev-list --all --count
  - echo version
  - git describe --tags
  - echo $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: SVka7J99K5/DGL8LVEEnMqX5vIAVw6/bUDJbC41TdKASfWR3Huy97I8xkwiJ947b2eGIlmwVJLR9GD6akeVaUUvpTKr0PXAm7nMdFrkfAaN5ovruqrcnjIYQ/Y0u3yj2JESAuQIpR4ggJ9xWu1OwVfDpDfIFCsLlAKMyok+Bc5/J3SCnAfly0X61e+rs+223pc8GW3Dvaqp/cMo5OiCfhebvVMmXIAENjvKYdciTnxjz5DRzsBDwzSZW/mRn96wgdroGOuoBYUll8EOoHD/yPCbmrRZcvk/DCvRojvwMmOvP7g38DcIbmvYr04MKnHyfvkAWNZNR0k2k5IIe+b2j7HPHqv6g6LN2nysarjW0kA+EzMq9R8lyaLwY1umzs3iavc/BQBVYggP8ItN4cO1gAfefm2dB8Wt9cH7Sr3OJpvQPNDMS1RNhjl0Xo9fR5uLy0BN7n31f3OcChfyOpsM0zFUZGvL7WrxMtABH6lG9DuCzvXvLaThsZQAXNcZyzrwdQMK2YVd//WUuOSiLwq207fa2hadV6q+PpEsX4M1ugOB4Z7FyQ0Se9kzYPgXKrfdtOvbt2yeLYUpUBW6qh+rQ7JMhRG0xK9x9MYZdmf096+0HqC+CVM4/zE0+dpnc8fagL44Wfrs825kUI7sBpgKp6cJQNGSlrZCCda/sJbmddQo=
  file: "app/build/outputs/apk/release/Cimoc.apk"
  skip_cleanup: true
  on:
    repo: feilongfl/Cimoc
    branch:
      - release-tci
    tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f2c42f2c1f06e4ac7bd0
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always