language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - add-on
  - extra
licenses:
- android-sdk-license-.+
before_install:
- echo $TRAVIS_BUILD_NUMBER
- yes | sdkmanager "platforms;android-29"
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
#- "./gradlew assembleRelease"
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew assembleRelease; fi'
before_deploy:
  - echo gitVersion
  - git rev-list --all --count
  - echo version
  - git describe --tags
  - echo $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: app/build/outputs/apk/release/Cimoc.apk
  on:
    repo: haleydu-test/Cimoc
    branch: release-tci
    tags: true
  skip_cleanup: true

