language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - add-on
  - extra
licenses:
- android-sdk-license-.+
before_install:
- echo $TRAVIS_BUILD_NUMBER
- yes | sdkmanager "platforms;android-29"
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
#- "./gradlew assembleRelease"
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew assembleRelease; fi'
before_deploy:
  - echo gitVersion
  - git rev-list --all --count
  - echo version
  - git describe --tags
  - echo $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
    secure: E9xS1Hsc6R7Yz/+ViS+2IrFxh4jeBobnr23OALY0jcLvXef0fH0d6r8hmYWFotc4PTU0gtQDAb+sqgGxPECJ6lxY+pZ30YeTeUlgCvioSL8Ud7hXaSGoRQ0BjDlkRpy4VIUOFiHITuOUuTKFhY2oa7KRFmw2qy9L2XFDXRanAlnxYFrtAffxSZFa589X2UR/Dw2kezyEYMhW3gpRH8mXoSf2SqUGfEB3EMNL/AeC2OoJVUmmJDoNqlFBY6a8uaO4XzisbGlWM423lRtGl2p31SxkRX7LK3MXZk7UsnLRzFmdEoTxS6tBahc6d+xtI3aVeG5CTzakhq12egdkWf9RHH9LRGuXe1n2CMtwaLyvz+lyVMGRwZ3Dwo9O4J/4EKtYiUBqu9kemkmTQSu25BDkH8sgiAnP+q4+JZuRh+8L5bllgJEjycHe3xhiwDsbyguDKOsBzn0VS171Dd92a7F73OHXQz5//aH7lEAVX7uFYW2Ak3Trgzb/S3Odn/S2B3cbnmc6eyNoeltbcw8WBdZYd0wONSV5nklI9ewUfQ5ZU2CuQLy3wh8hAdcjefqxDEqL1p+phLCA57uq/7Zk9pNSEploJu7E0+acIaLt+OoMd2gDdao+wRS/g4g8X3rEme8pCPeX9DQ8QrqzxNNC4vCJX2LHVEdBhtgLlhSyGT5V+YQ=
  file: "app/build/outputs/apk/release/Cimoc.apk"
  skip_cleanup: true
  on:
    repo: Haleydu/Cimoc
    branch:
      - release-tci
    tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f2c42f2c1f06e4ac7bd0
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always